# Generated by Django 3.2.13 on 2022-11-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
    ]
