# Generated by Django 3.2.13 on 2022-12-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221202_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('자료공유', '자료공유'), ('질문', '질문'), ('취업', '취업'), ('잡담', '잡담')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
