# Generated by Django 3.2.13 on 2022-12-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_content'),
        ('articles', '0005_article_category'),
    ]

    operations = [
    ]
