# Generated by Django 3.2.13 on 2022-12-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_merge_20221204_2302'),
        ('articles', '0006_merge_20221205_0001'),
    ]

    operations = [
    ]
