# Generated by Django 3.2.13 on 2022-12-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_merge_20221205_0913'),
        ('articles', '0007_merge_20221205_0924'),
    ]

    operations = [
    ]
