# Generated by Django 3.2.13 on 2022-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BJData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
    ]
