# Generated by Django 3.2.13 on 2022-12-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_rename_bjdata_bjdata_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BJData_br',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BJData_di',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BJData_go',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BJData_pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BJData_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BJData_si',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BJData_1',
        ),
    ]
