# Generated by Django 3.2.13 on 2022-12-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_number',
            field=models.IntegerField(default=0),
        ),
    ]
