# Generated by Django 3.2.13 on 2022-11-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookarticle',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guestbookcomment',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
