# Generated by Django 3.2.13 on 2022-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_message_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boj_tier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
