# Generated by Django 3.2.13 on 2022-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221201_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notice_note',
            field=models.BooleanField(default=True),
        ),
    ]
