# Generated by Django 3.2.13 on 2022-11-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221130_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookarticle',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guestbookcomment',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
