# Generated by Django 3.2.13 on 2022-12-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note_notice',
            field=models.BooleanField(default=True),
        ),
    ]
