# Generated by Django 3.2.13 on 2022-12-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_mbti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message_number',
        ),
    ]
