# Generated by Django 3.2.13 on 2022-12-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('JavaScript', 'JavaScript'), ('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('PHP', 'PHP')], max_length=10),
        ),
    ]
