# Generated by Django 3.2.13 on 2022-12-02 10:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221202_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Django', 'Django'), ('Spring', 'Spring'), ('Node.js', 'Node.js'), ('React', 'React'), ('MySQL', 'MySQL'), ('SQLite', 'SQLite')], max_length=40),
        ),
    ]
