# Generated by Django 3.2.13 on 2022-11-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_guestbookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookarticle',
            name='guestbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestbook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestbookcomment',
            name='guestbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestbook'),
            preserve_default=False,
        ),
    ]
