# Generated by Django 3.2.13 on 2022-11-29 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221128_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookcomment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestbookarticle'),
        ),
    ]
