# Generated by Django 3.2.13 on 2022-11-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221129_1123'),
        ('accounts', '0010_alter_guestbookcomment_article'),
    ]

    operations = [
    ]
