# Generated by Django 3.2.13 on 2022-11-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221129_1553'),
        ('accounts', '0012_auto_20221129_1613'),
    ]

    operations = [
    ]
