# Generated by Django 3.2.13 on 2022-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='to_id',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
