# Generated by Django 3.2.13 on 2022-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='career',
            field=models.CharField(choices=[('1년 미만', '1년 미만'), ('1년 이상', '1년 이상'), ('2년 이상', '2년 이상'), ('3년 이상', '3년 이상'), ('4년 이상', '4년 이상'), ('5년 이상', '5년 이상'), ('시니어', '시니어')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='daily_learning_hours',
            field=models.CharField(choices=[('1시간 미만', '1시간 미만'), ('1시간 이상 3시간 미만', '1시간 이상 3시간 미만'), ('3시간 이상 5시간 미만', '3시간 이상 5시간 미만'), ('5시간 이상 10시간 미만', '5시간 이상 10시간 미만'), ('10시간 이상', '10시간 이상')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='degree',
            field=models.CharField(choices=[('없음', '없음'), ('전문학사', '전문학사'), ('학사', '학사'), ('석사', '석사'), ('박사', '박사')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='desired_language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('HTML/CSS', 'HTML/CSS'), ('기타', '기타')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='developer_type',
            field=models.CharField(choices=[('풀스택 개발자', '풀스택 개발자'), ('백엔드 개발자', '백엔드 개발자'), ('프론트엔드 개발자', '프론트엔드 개발자'), ('기타', '기타')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='education',
            field=models.CharField(choices=[('중졸 이하', '중졸 이하'), ('고졸', '고졸'), ('전문대졸', '전문대졸'), ('대졸 이상', '대졸 이상')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성'), ('제3의 성', '제3의 성')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='how_to_learn',
            field=models.CharField(choices=[('학교', '학교'), ('책', '책'), ('코딩 부트캠프', '코딩 부트캠프'), ('온라인 강의', '온라인 강의'), ('기타 자료 (동영상, 블로그 등)', '기타 자료 (동영상, 블로그 등)'), ('기타', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='most_using_language',
            field=models.CharField(choices=[('Python', 'Python'), ('C', 'C'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('HTML/CSS', 'HTML/CSS'), ('기타', '기타')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_age',
            field=models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대', '60대'), ('70살 이상', '70살 이상')], max_length=10),
        ),
    ]
