# Generated by Django 3.2.13 on 2022-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20221203_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='education',
        ),
        migrations.AlterField(
            model_name='survey',
            name='degree',
            field=models.CharField(choices=[('고졸', '고졸'), ('전문학사', '전문학사'), ('학사', '학사'), ('석사', '석사'), ('박사', '박사')], max_length=20),
        ),
    ]
