# Generated by Django 3.2.13 on 2022-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20221205_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='daily_learning_hours',
            field=models.CharField(choices=[('1시간 이상', '1시간 이상'), ('2시간 이상', '2시간 이상'), ('3시간 이상', '3시간 이상'), ('5시간 이상', '5시간 이상'), ('10시간 이상', '10시간 이상')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='developer_type',
            field=models.CharField(choices=[('풀스택', '풀스택'), ('백엔드', '백엔드'), ('프론트엔드', '프론트엔드'), ('기타', '기타')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='how_to_learn',
            field=models.CharField(choices=[('학교', '학교'), ('책', '책'), ('부트캠프', '부트캠프'), ('온라인 강의', '온라인 강의'), ('기타', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_age',
            field=models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대')], max_length=10),
        ),
    ]
