# Generated by Django 3.2.13 on 2022-12-08 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('알고리즘 공부', '알고리즘 공부'), ('프론트엔드 공부', '프론트엔드 공부'), ('백엔드 공부', '백엔드 공부'), ('기타', '기타')], max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('limit', models.IntegerField(default=2)),
                ('is_closed', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='study_images/')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
