# Generated by Django 3.2.13 on 2022-12-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_remove_studynotice_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotice',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studies.study'),
            preserve_default=False,
        ),
    ]
