# Generated by Django 3.2.13 on 2022-12-09 13:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_auto_20221209_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='study_images/'),
        ),
    ]
