# Generated by Django 3.2.13 on 2022-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_alter_study_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studynotice',
            name='study',
        ),
        migrations.AddField(
            model_name='studynotice',
            name='study_title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
