# Generated by Django 3.2.13 on 2022-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_studynotice_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='image',
            field=models.ImageField(upload_to='study_images/'),
        ),
    ]
