# Generated by Django 3.2.13 on 2022-12-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_alter_study_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='contact',
            field=models.EmailField(max_length=50),
        ),
    ]
