# Generated by Django 3.2.13 on 2022-12-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_alter_study_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='image',
            field=models.ImageField(blank=True, upload_to='study_images/'),
        ),
    ]
