# Generated by Django 3.2.13 on 2022-12-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_article_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studies.study'),
            preserve_default=False,
        ),
    ]
