# Generated by Django 3.2.13 on 2022-12-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_article_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='study',
        ),
    ]
