# Generated by Django 3.2.13 on 2022-12-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0015_auto_20221213_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('문제', '문제'), ('질문', '질문'), ('자유 게시판', '자유 게시판')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
