# Generated by Django 3.2.13 on 2022-12-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_alter_study_image'),
        ('studies', '0016_board_category'),
    ]

    operations = [
    ]
