# Generated by Django 3.2.13 on 2022-12-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_merge_0013_alter_study_image_0016_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('문제', '문제'), ('질문', '질문'), ('잡담', '잡담')], max_length=10),
        ),
        migrations.AlterField(
            model_name='board',
            name='problem_number',
            field=models.IntegerField(null=True),
        ),
    ]
