# Generated by Django 3.2.13 on 2022-12-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_auto_20221214_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='problem_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
